[system]
imagePath=E:\Data
curSpec=A50
curId=1
K=0.07
IFGroup=true
imagedays=100
saveokimage=True
savengimage=True
First=MFG270525C3
Second=EXP271127CP
totalTimeCam1=0
totalTimeCam2=0
cameraDebug=0
Offset=0
IFInitCamera=False
Astrict=1
saveokrawimage=True
savengrawimage=True
[camera]
camera1sn=FC79423AAK00087
camera2sn=FC79423AAK00060
camera3sn=FB12474AAK00017
camera4sn=FB12474AAK00006
camera5sn=EM57578AAK00046
camera6sn=EM57578AAK00010
camera7sn=EK64117CAK00003
camera8sn=EK64117CAK00004
[count1]
total=9776
ng=23772
ok=9720
ng_camera1=11890
ng_camera2=11883
ng_char=0
total_char=6
ok_char=6
ng_cam1=0
ng_cam2=3
ng_cam3=0
ng_cam5=0
ng_cam4=53
[modbus]
modbusIP=192.168.1.88
modbusPort=502
[StandChar]
Camera1Ignore=True
Camera2Ignore=True
[control]
ipaddr=192.168.0.11

[AI_Models]
ModelRootPath=.\AI\Models
; 正面模型
FrontPCodeOcrModel=正面\P号码识别\model.vimosln
FrontBoxBreakModel=正面\盒子破检测\best.onnx
;FrontFilmBreakModel=正面\薄膜破检测\best.onnx
; 端面模型
EndFaceUpperModel=端面\上端面\best.onnx
EndFaceLowerModel=端面\下端面\best.onnx
; 背面模型
;BackBarcodeModel=背面\条形码识别\best.onnx
;BackDateCodeModel=背面\日期码识别\model.vimosln
BackHookDamageModel=背面\明显挂钩错位\best.onnx
BackHookSlightModel=背面\轻微挂钩错位\best.onnx
;BackCutCharModel=背面\切字识别\model.vimosln
; 侧面模型
SideDefectModel=侧面\缺陷检测\best.onnx
; GPU配置
UseGpu=True
VimoGpuDeviceId=1      ; Vimo模型(.vimosln)使用显卡1
YoloGpuDeviceId=0      ; Yolo模型(.onnx)使用显卡0
; 输入端口配置
[input_port]
cam1=9      ; 正面到位
cam2=10     ; 端面到位
cam3=11     ; 背面到位
cam4=12     ; 侧面触发（运动轴上）
cam5=13     ; 侧面到位
; 输出端口配置
[output_port]
cam1=8      ; 正面左相机触发
cam2=9      ; 正面右相机触发
cam3=10     ; 背面左相机触发
cam4=11     ; 背面右相机触发
cam5=12     ; 上端面相机触发
cam6=13     ; 下端面相机触发
cam7=14     ; 左侧面相机触发
cam8=15     ; 右侧面相机触发
; 脉冲宽度
[pulse_width]
default=50  ; 默认50ms
